/*
 * Copyright (c) 2019 BITMAIN
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#include <dt-bindings/clock/bm1880-clock.h>
#include "clk.h"

/* PLL clocks */
struct bm_pll_clock root_pll_clks[] = {
	{
		.id = FPLL_CLK,
		.name = "fpll_clk",
		.parent_name = "osc1",
		.flags = CLK_GET_RATE_NOCACHE | CLK_GET_ACCURACY_NOCACHE,
		.ini_flags = BM_CLK_RO,
		.status_offset = 0xc0,
		.pctrl_table = { {NORMAL_MODE, (1500 * MHZ)}, {FAST_MODE, (1500 * MHZ)},
		{SAFE_MODE, (1500 * MHZ)}, {BYPASS_MODE, (25 * MHZ)} },
	},
	{
		.id = SPLL_CLK,
		.name = "spll_clk",
		.parent_name = "osc1",
		.flags = CLK_GET_RATE_NOCACHE | CLK_GET_ACCURACY_NOCACHE,
		.status_offset = 0xc0,
		.pctrl_table = { {NORMAL_MODE, (775 * MHZ), 62, 1, 1, 2}, {FAST_MODE, (1000 * MHZ), 80, 1, 1, 2},
		{SAFE_MODE, (700 * MHZ), 56, 1, 1, 2}, {BYPASS_MODE, (25 * MHZ), 40, 1, 1, 2} },
	},
	{
		.id = DPLL_CLK,
		.name = "dpll_clk",
		.parent_name = "osc1",
		.flags = CLK_GET_RATE_NOCACHE | CLK_GET_ACCURACY_NOCACHE,
		.status_offset = 0xc0,
		.pctrl_table = { {NORMAL_MODE, (1200 * MHZ), 96, 1, 1, 2}, {FAST_MODE, (1600 * MHZ), 128, 1, 1, 2},
		{SAFE_MODE, (800 * MHZ), 64, 1, 1, 2}, {BYPASS_MODE, (25 * MHZ), 40, 1, 1, 2} },
	},
	{
		.id = MPLL_CLK,
		.name = "mpll_clk",
		.parent_name = "osc1",
		.flags = CLK_GET_RATE_NOCACHE | CLK_GET_ACCURACY_NOCACHE,
		.status_offset = 0xc0,
		.pctrl_table = { {NORMAL_MODE, (1150 * MHZ), 92, 1, 1, 2}, {FAST_MODE, (1500 * MHZ), 120, 1, 1, 2},
		{SAFE_MODE, (750 * MHZ), 60, 1, 1, 2}, {BYPASS_MODE, (25 * MHZ), 40, 1, 1, 2} },
	},
};

/* gate clocks */
struct bm_gate_clock gate_clks[] = {
	{ GATE_CLK_NF, "gate_clk_nf", "div_clk_nf",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 31, 0, },
	{ GATE_CLK_APB_NF, "gate_clk_apb_nf", "gate_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 30, 0, },
	{ GATE_CLK_AXI5_NF, "gate_clk_axi5_nf", "gate_clk_axi5",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 29, 0, },
	{ GATE_CLK_JPEG_AXI, "gate_clk_jpeg_axi", "div_clk_jpeg_axi",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 28, 0, },
	{ GATE_CLK_APB_JPEG, "gate_clk_apb_jpeg", "gate_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 27, 0, },
	{ GATE_CLK_APB_WDT, "gate_clk_apb_wdt", "mux_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 26, 0, },
	{ GATE_CLK_APB_I2C, "gate_clk_apb_i2c", "mux_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 25, 0, },
	{ GATE_CLK_SDMA_AUD, "gate_clk_sdma_aud", "div_clk_sdma_aud",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 24, 0, },
	{ GATE_CLK_SDMA_AXI, "gate_clk_sdma_axi", "gate_clk_axi5",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 23, 0, },
	{ GATE_CLK_AHB_SF, "gate_clk_ahb_sf", "mux_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 22, 0, },
	{ GATE_CLK_AXI1_MINER, "gate_clk_axi1_miner", "gate_clk_axi1",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 21, 0, },
	{ GATE_CLK_GPIO_DB, "gate_clk_gpio_db", "div_clk_gpio_db",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 20, 0, },
	{ GATE_CLK_APB_GPIO_INTR, "gate_clk_apb_gpio_intr", "mux_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 19, 0, },
	{ GATE_CLK_APB_GPIO, "gate_clk_apb_gpio", "mux_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 18, 0, },
	{ GATE_CLK_AXI1_GDMA, "gate_clk_axi1_gdma", "gate_clk_axi1",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 17, 0, },
	{ GATE_CLK_AXI4_ETH1, "gate_clk_axi4_eth1", "gate_clk_axi4",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 16, 0, },
	{ GATE_CLK_500M_ETH1, "gate_clk_500m_eth1", "div_clk_500m_eth1",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 15, 0, },
	{ GATE_CLK_AXI4_ETH0, "gate_clk_axi4_eth0", "gate_clk_axi4",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 14, 0, },
	{ GATE_CLK_500M_ETH0, "gate_clk_500m_eth0", "div_clk_500m_eth0",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 13, 0, },
	{ GATE_CLK_100K_SD, "gate_clk_100k_sd", "div_clk_100k_sd",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 12, 0, },
	{ GATE_CLK_SD, "gate_clk_sd", "div_clk_sd",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 11, 0, },
	{ GATE_CLK_AXI5_SD, "gate_clk_axi5_sd", "gate_clk_axi5",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 10, 0, },
	{ GATE_CLK_100K_EMMC, "gate_clk_100k_emmc", "div_clk_100k_emmc",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 9, 0, },
	{ GATE_CLK_EMMC, "gate_clk_emmc", "div_clk_emmc",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 8, 0, },
	{ GATE_CLK_AXI5_EMMC, "gate_clk_axi5_emmc", "gate_clk_axi5",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 7, 0, },
	{ GATE_CLK_APB_EFUSE, "gate_clk_apb_efuse", "mux_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 6, 0, },
	{ GATE_CLK_EFUSE, "gate_clk_efuse", "div_clk_efuse",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 5, 0, },
	{ GATE_CLK_DDR_AXI_REG, "gate_clk_ddr_axi_reg", "mux_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 4, 0, },
	{ GATE_CLK_AXI1_AXISRAM, "gate_clk_axi1_axisram", "gate_clk_axi1",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 3, 0, },
	{ GATE_CLK_AHB_ROM, "gate_clk_ahb_rom", "mux_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 2, 0, },
	{ GATE_CLK_50M_A53, "gate_clk_50m_a53", "div_clk_50m_a53",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 1, 0, },
	{ GATE_CLK_A53, "gate_clk_a53", "mux_clk_a53",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x800, 0, 0, },
	{ GATE_CLK_AXI6, "gate_clk_axi6", "mux_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 21, 0, },
	{ GATE_CLK_AXI5, "gate_clk_axi5", "div_clk_axi5",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 20, 0, },
	{ GATE_CLK_AXI4, "gate_clk_axi4", "div_clk_axi4",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 19, 0, },
	{ GATE_CLK_AXI3, "gate_clk_axi3", "div_clk_axi3",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 18, 0, },
	{ GATE_CLK_AXI2, "gate_clk_axi2", "div_clk_axi2",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 17, 0, },
	{ GATE_CLK_AXI1, "gate_clk_axi1", "mux_clk_axi1",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 16, 0, },
	{ GATE_CLK_APB_VPP, "gate_clk_apb_vpp", "gate_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 15, 0, },
	{ GATE_CLK_VPP_AXI, "gate_clk_vpp_axi", "div_clk_vpp_axi",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 14, 0, },
	{ GATE_CLK_VIDEO_AXI, "gate_clk_video_axi", "div_clk_video_axi",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 13, 0, },
	{ GATE_CLK_APB_VIDEO, "gate_clk_apb_video", "gate_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 12, 0, },
	{ GATE_CLK_12M_USB, "gate_clk_12m_usb", "div_clk_12m_usb",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 11, 0, },
	{ GATE_CLK_33K_USB, "gate_clk_33k_usb", "div_clk_33k_usb",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 10, 0, },
	{ GATE_CLK_125M_USB, "gate_clk_125m_usb", "div_clk_125m_usb",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 9, 0, },
	{ GATE_CLK_APB_USB, "gate_clk_apb_usb", "gate_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 8, 0, },
	{ GATE_CLK_AXI4_USB, "gate_clk_axi4_usb", "gate_clk_axi4",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 7, 0, },
	{ GATE_CLK_APB_I2S, "gate_clk_apb_i2s", "gate_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 6, 0, },
	{ GATE_CLK_APB_UART, "gate_clk_apb_uart", "gate_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 5, 0, },
	{ GATE_CLK_UART_500M, "gate_clk_uart_500m", "div_clk_uart_500m",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 4, 0, },
	{ GATE_CLK_TPU_AXI, "gate_clk_tpu_axi", "div_clk_tpu_axi",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 3, 0, },
	{ GATE_CLK_APB_SPI, "gate_clk_apb_spi", "mux_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 2, 0, },
	{ GATE_CLK_RV, "gate_clk_rv", "mux_clk_rv",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 1, 0, },
	{ GATE_CLK_APB_PWM, "gate_clk_apb_pwm", "mux_clk_axi6",
		CLK_SET_RATE_PARENT | CLK_IGNORE_UNUSED, 0x804, 0, 0, },
};

/* mux clocks */
const char *const mux_clk_axi6_p[] = {"div_1_clk_axi6", "div_0_clk_axi6"};
const char *const mux_clk_axi1_p[] = {"div_1_clk_axi1", "div_0_clk_axi1"};
const char *const mux_clk_rv_p[] = {"div_1_clk_rv", "div_0_clk_rv"};
const char *const mux_clk_a53_p[] = {"spll_clk", "mpll_clk"};

struct bm_mux_clock mux_clks[] = {
	{
		MUX_CLK_AXI6, "mux_clk_axi6", mux_clk_axi6_p,
		ARRAY_SIZE(mux_clk_axi6_p),
		CLK_SET_RATE_PARENT | CLK_SET_RATE_NO_REPARENT,
		0x820, 3, 1, 0,
	},
	{
		MUX_CLK_AXI1, "mux_clk_axi1", mux_clk_axi1_p,
		ARRAY_SIZE(mux_clk_axi1_p),
		CLK_SET_RATE_PARENT | CLK_SET_RATE_NO_REPARENT,
		0x820, 2, 1, 0,
	},
	{
		MUX_CLK_RV, "mux_clk_rv", mux_clk_rv_p,
		ARRAY_SIZE(mux_clk_rv_p),
		CLK_SET_RATE_PARENT | CLK_SET_RATE_NO_REPARENT,
		0x820, 1, 1, 0,
	},
	{
		MUX_CLK_A53, "mux_clk_a53", mux_clk_a53_p,
		ARRAY_SIZE(mux_clk_a53_p),
		CLK_SET_RATE_PARENT | CLK_SET_RATE_NO_REPARENT,
		0x820, 0, 1, 0,
	},
};

/* divider clocks */
struct bm_divider_clock div_clks[] = {
	{ DIV_CLK_50M_A53, "div_clk_50m_a53", "fpll_clk",
		0, 0x840, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 30, },
	{ DIV_CLK_EFUSE, "div_clk_efuse", "fpll_clk",
		0, 0x844, 16, 7,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 60, },
	{ DIV_CLK_EMMC, "div_clk_emmc", "fpll_clk",
		0, 0x848, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 15, },
	{ DIV_CLK_100K_EMMC, "div_clk_100k_emmc", "div_clk_12m_usb",
		0, 0x84C, 16, 8,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 120, },
	{ DIV_CLK_SD, "div_clk_sd", "fpll_clk",
		0, 0x850, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 15, },
	{ DIV_CLK_100K_SD, "div_clk_100k_sd", "div_clk_12m_usb",
		0, 0x854, 16, 8,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 120, },
	{ DIV_CLK_500M_ETH0, "div_clk_500m_eth0", "fpll_clk",
		0, 0x858, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 3, },
	{ DIV_CLK_500M_ETH1, "div_clk_500m_eth1", "fpll_clk",
		0, 0x85C, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 3, },
	{ DIV_CLK_GPIO_DB, "div_clk_gpio_db", "div_clk_12m_usb",
		0, 0x860, 16, 16,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 120, },
	{ DIV_CLK_SDMA_AUD, "div_clk_sdma_aud", "fpll_clk",
		0, 0x864, 16, 7,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 61, },
	{ DIV_CLK_JPEG_AXI, "div_clk_jpeg_axi", "fpll_clk",
		0, 0x868, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 4, },
	{ DIV_CLK_NF, "div_clk_nf", "fpll_clk",
		0, 0x86C, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 30, },
	{ DIV_0_CLK_RV, "div_0_clk_rv", "spll_clk",
		0, 0x870, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 1, },
	{ DIV_1_CLK_RV, "div_1_clk_rv", "fpll_clk",
		0, 0x874, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 1, },
	{ DIV_CLK_TPU_AXI, "div_clk_tpu_axi", "spll_clk",
		0, 0x878, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 1, },
	{ DIV_CLK_UART_500M, "div_clk_uart_500m", "fpll_clk",
		0, 0x87C, 16, 7,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 3, },
	{ DIV_CLK_125M_USB, "div_clk_125m_usb", "fpll_clk",
		0, 0x880, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 12, },
	{ DIV_CLK_33K_USB, "div_clk_33k_usb", "div_clk_12m_usb",
		0, 0x884, 16, 9,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 363, },
	{ DIV_CLK_12M_USB, "div_clk_12m_usb", "fpll_clk",
		0, 0x888, 16, 7,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 125, },
	{ DIV_CLK_VIDEO_AXI, "div_clk_video_axi", "fpll_clk",
		0, 0x88C, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 4, },
	{ DIV_CLK_VPP_AXI, "div_clk_vpp_axi", "fpll_clk",
		0, 0x890, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 4, },
	{ DIV_0_CLK_AXI1, "div_0_clk_axi1", "mpll_clk",
		0, 0x894, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 2, },
	{ DIV_1_CLK_AXI1, "div_1_clk_axi1", "fpll_clk",
		0, 0x898, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 3, },
	{ DIV_CLK_AXI2, "div_clk_axi2", "fpll_clk",
		0, 0x89C, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 3, },
	{ DIV_CLK_AXI3, "div_clk_axi3", "mux_clk_rv",
		0, 0x8A0, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 2, },
	{ DIV_CLK_AXI4, "div_clk_axi4", "fpll_clk",
		0, 0x8A4, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 6, },
	{ DIV_CLK_AXI5, "div_clk_axi5", "fpll_clk",
		0, 0x8A8, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 15, },
	{ DIV_0_CLK_AXI6, "div_0_clk_axi6", "fpll_clk",
		0, 0x8AC, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 15, },
	{ DIV_1_CLK_AXI6, "div_1_clk_axi6", "mpll_clk",
		0, 0x8B0, 16, 5,
		CLK_DIVIDER_ONE_BASED | CLK_DIVIDER_ALLOW_ZERO,
		BM_CLK_USE_INIT_VAL, 11, },
};

struct bm_clk_table pll_clk_tables = {
		.pll_clks_num = ARRAY_SIZE(root_pll_clks),
		.pll_clks = root_pll_clks,
};

struct bm_clk_table div_clk_tables[] = {
	{
		.id = DIV_CLK_TABLE,
		.div_clks_num = ARRAY_SIZE(div_clks),
		.div_clks = div_clks,
		.gate_clks_num = ARRAY_SIZE(gate_clks),
		.gate_clks = gate_clks,
	},
};

struct bm_clk_table mux_clk_tables[] = {
	{
		.id = MUX_CLK_TABLE,
		.mux_clks_num = ARRAY_SIZE(mux_clks),
		.mux_clks = mux_clks,
	},
};

unsigned int size_div_clk_tables = ARRAY_SIZE(div_clk_tables);
unsigned int size_mux_clk_tables = ARRAY_SIZE(mux_clk_tables);
