ln -s /bin/busybox usr/bin/[
ln -s /bin/busybox usr/bin/[[
ln -s /bin/busybox sbin/acpid
ln -s /bin/busybox usr/sbin/add-shell
ln -s /bin/busybox usr/sbin/addgroup
ln -s /bin/busybox usr/sbin/adduser
ln -s /bin/busybox sbin/adjtimex
ln -s /bin/busybox sbin/arp
ln -s /bin/busybox usr/sbin/arping
ln -s /bin/busybox bin/ash
ln -s /bin/busybox usr/bin/awk
ln -s /bin/busybox bin/base64
ln -s /bin/busybox usr/bin/basename
ln -s /bin/busybox usr/bin/beep
ln -s /bin/busybox usr/bin/blkdiscard
ln -s /bin/busybox sbin/blkid
ln -s /bin/busybox sbin/blockdev
ln -s /bin/busybox sbin/bootchartd
ln -s /bin/busybox usr/sbin/brctl
ln -s /bin/busybox usr/bin/bunzip2
ln -s /bin/busybox usr/bin/bzcat
ln -s /bin/busybox usr/bin/bzip2
ln -s /bin/busybox usr/bin/cal
ln -s /bin/busybox bin/cat
ln -s /bin/busybox usr/sbin/chat
ln -s /bin/busybox bin/chattr
ln -s /bin/busybox bin/chgrp
ln -s /bin/busybox bin/chmod
ln -s /bin/busybox bin/chown
ln -s /bin/busybox usr/sbin/chpasswd
ln -s /bin/busybox usr/bin/chpst
ln -s /bin/busybox usr/sbin/chroot
ln -s /bin/busybox usr/bin/chrt
ln -s /bin/busybox usr/bin/chvt
ln -s /bin/busybox usr/bin/cksum
ln -s /bin/busybox usr/bin/clear
ln -s /bin/busybox usr/bin/cmp
ln -s /bin/busybox usr/bin/comm
ln -s /bin/busybox bin/conspy
ln -s /bin/busybox bin/cp
ln -s /bin/busybox bin/cpio
ln -s /bin/busybox usr/sbin/crond
ln -s /bin/busybox usr/bin/crontab
ln -s /bin/busybox usr/bin/cryptpw
ln -s /bin/busybox bin/cttyhack
ln -s /bin/busybox usr/bin/cut
ln -s /bin/busybox bin/date
ln -s /bin/busybox usr/bin/dc
ln -s /bin/busybox bin/dd
ln -s /bin/busybox usr/bin/deallocvt
ln -s /bin/busybox usr/sbin/delgroup
ln -s /bin/busybox usr/sbin/deluser
ln -s /bin/busybox sbin/depmod
ln -s /bin/busybox sbin/devmem
ln -s /bin/busybox bin/df
ln -s /bin/busybox usr/sbin/dhcprelay
ln -s /bin/busybox usr/bin/diff
ln -s /bin/busybox usr/bin/dirname
ln -s /bin/busybox bin/dmesg
ln -s /bin/busybox usr/sbin/dnsd
ln -s /bin/busybox bin/dnsdomainname
ln -s /bin/busybox usr/bin/dos2unix
ln -s /bin/busybox usr/bin/dpkg
ln -s /bin/busybox usr/bin/dpkg-deb
ln -s /bin/busybox usr/bin/du
ln -s /bin/busybox bin/dumpkmap
ln -s /bin/busybox usr/bin/dumpleases
ln -s /bin/busybox bin/echo
ln -s /bin/busybox bin/ed
ln -s /bin/busybox bin/egrep
ln -s /bin/busybox usr/bin/eject
ln -s /bin/busybox usr/bin/env
ln -s /bin/busybox usr/bin/envdir
ln -s /bin/busybox usr/bin/envuidgid
ln -s /bin/busybox usr/sbin/ether-wake
ln -s /bin/busybox usr/bin/expand
ln -s /bin/busybox usr/bin/expr
ln -s /bin/busybox usr/bin/factor
ln -s /bin/busybox usr/sbin/fakeidentd
ln -s /bin/busybox usr/bin/fallocate
ln -s /bin/busybox bin/false
ln -s /bin/busybox bin/fatattr
ln -s /bin/busybox usr/sbin/fbset
ln -s /bin/busybox sbin/fbsplash
ln -s /bin/busybox bin/fdflush
ln -s /bin/busybox usr/sbin/fdformat
ln -s /bin/busybox sbin/fdisk
ln -s /bin/busybox usr/bin/fgconsole
ln -s /bin/busybox bin/fgrep
ln -s /bin/busybox usr/bin/find
ln -s /bin/busybox sbin/findfs
ln -s /bin/busybox usr/bin/flock
ln -s /bin/busybox usr/bin/fold
ln -s /bin/busybox usr/bin/free
ln -s /bin/busybox sbin/freeramdisk
ln -s /bin/busybox sbin/fsck
ln -s /bin/busybox sbin/fsck.minix
ln -s /bin/busybox usr/sbin/fsfreeze
ln -s /bin/busybox sbin/fstrim
ln -s /bin/busybox bin/fsync
ln -s /bin/busybox usr/sbin/ftpd
ln -s /bin/busybox usr/bin/ftpget
ln -s /bin/busybox usr/bin/ftpput
ln -s /bin/busybox usr/bin/fuser
ln -s /bin/busybox bin/getopt
ln -s /bin/busybox sbin/getty
ln -s /bin/busybox bin/grep
ln -s /bin/busybox usr/bin/groups
ln -s /bin/busybox bin/gunzip
ln -s /bin/busybox bin/gzip
ln -s /bin/busybox sbin/halt
ln -s /bin/busybox usr/bin/hd
ln -s /bin/busybox sbin/hdparm
ln -s /bin/busybox usr/bin/head
ln -s /bin/busybox usr/bin/hexdump
ln -s /bin/busybox usr/bin/hostid
ln -s /bin/busybox bin/hostname
ln -s /bin/busybox usr/sbin/httpd
ln -s /bin/busybox bin/hush
ln -s /bin/busybox sbin/hwclock
ln -s /bin/busybox usr/sbin/i2cdetect
ln -s /bin/busybox usr/sbin/i2cdump
ln -s /bin/busybox usr/sbin/i2cget
ln -s /bin/busybox usr/sbin/i2cset
ln -s /bin/busybox usr/bin/id
ln -s /bin/busybox sbin/ifdown
ln -s /bin/busybox sbin/ifenslave
ln -s /bin/busybox usr/sbin/ifplugd
ln -s /bin/busybox sbin/ifup
ln -s /bin/busybox usr/sbin/inetd
ln -s /bin/busybox sbin/init
ln -s /bin/busybox sbin/insmod
ln -s /bin/busybox usr/bin/install
ln -s /bin/busybox bin/ionice
ln -s /bin/busybox bin/iostat
ln -s /bin/busybox sbin/ip
ln -s /bin/busybox sbin/ipaddr
ln -s /bin/busybox bin/ipcalc
ln -s /bin/busybox usr/bin/ipcrm
ln -s /bin/busybox usr/bin/ipcs
ln -s /bin/busybox sbin/iplink
ln -s /bin/busybox sbin/ipneigh
ln -s /bin/busybox sbin/iproute
ln -s /bin/busybox sbin/iprule
ln -s /bin/busybox sbin/iptunnel
ln -s /bin/busybox bin/kbd_mode
ln -s /bin/busybox bin/kill
ln -s /bin/busybox usr/bin/killall
ln -s /bin/busybox usr/sbin/killall5
ln -s /bin/busybox sbin/klogd
ln -s /bin/busybox usr/bin/last
ln -s /bin/busybox usr/bin/less
ln -s /bin/busybox bin/link
ln -s /bin/busybox bin/linux32
ln -s /bin/busybox bin/linux64
ln -s /bin/busybox bin/ln
ln -s /bin/busybox usr/sbin/loadfont
ln -s /bin/busybox sbin/loadkmap
ln -s /bin/busybox usr/bin/logger
ln -s /bin/busybox bin/login
ln -s /bin/busybox usr/bin/logname
ln -s /bin/busybox sbin/logread
ln -s /bin/busybox sbin/losetup
ln -s /bin/busybox usr/sbin/lpd
ln -s /bin/busybox usr/bin/lpq
ln -s /bin/busybox usr/bin/lpr
ln -s /bin/busybox bin/ls
ln -s /bin/busybox bin/lsattr
ln -s /bin/busybox sbin/lsmod
ln -s /bin/busybox usr/bin/lsof
ln -s /bin/busybox usr/bin/lspci
ln -s /bin/busybox usr/bin/lsscsi
ln -s /bin/busybox usr/bin/lsusb
ln -s /bin/busybox usr/bin/lzcat
ln -s /bin/busybox usr/bin/lzma
ln -s /bin/busybox bin/lzop
ln -s /bin/busybox sbin/makedevs
ln -s /bin/busybox bin/makemime
ln -s /bin/busybox usr/bin/man
ln -s /bin/busybox usr/bin/md5sum
ln -s /bin/busybox sbin/mdev
ln -s /bin/busybox usr/bin/mesg
ln -s /bin/busybox usr/bin/microcom
ln -s /bin/busybox bin/mkdir
ln -s /bin/busybox sbin/mkdosfs
ln -s /bin/busybox sbin/mke2fs
ln -s /bin/busybox usr/bin/mkfifo
ln -s /bin/busybox sbin/mkfs.ext2
ln -s /bin/busybox sbin/mkfs.minix
ln -s /bin/busybox sbin/mkfs.vfat
ln -s /bin/busybox bin/mknod
ln -s /bin/busybox usr/bin/mkpasswd
ln -s /bin/busybox sbin/mkswap
ln -s /bin/busybox bin/mktemp
ln -s /bin/busybox sbin/modinfo
ln -s /bin/busybox sbin/modprobe
ln -s /bin/busybox bin/more
ln -s /bin/busybox bin/mount
ln -s /bin/busybox bin/mountpoint
ln -s /bin/busybox bin/mpstat
ln -s /bin/busybox bin/mt
ln -s /bin/busybox bin/mv
ln -s /bin/busybox sbin/nameif
ln -s /bin/busybox usr/sbin/nanddump
ln -s /bin/busybox usr/sbin/nandwrite
ln -s /bin/busybox usr/sbin/nbd-client
ln -s /bin/busybox usr/bin/nc
ln -s /bin/busybox bin/netstat
ln -s /bin/busybox bin/nice
ln -s /bin/busybox usr/bin/nl
ln -s /bin/busybox usr/bin/nmeter
ln -s /bin/busybox usr/bin/nohup
ln -s /bin/busybox usr/bin/nproc
ln -s /bin/busybox usr/bin/nsenter
ln -s /bin/busybox usr/bin/nslookup
ln -s /bin/busybox usr/bin/od
ln -s /bin/busybox usr/bin/openvt
ln -s /bin/busybox usr/sbin/partprobe
ln -s /bin/busybox usr/bin/passwd
ln -s /bin/busybox usr/bin/paste
ln -s /bin/busybox usr/bin/patch
ln -s /bin/busybox usr/bin/pgrep
ln -s /bin/busybox bin/pidof
ln -s /bin/busybox bin/ping
ln -s /bin/busybox bin/ping6
ln -s /bin/busybox bin/pipe_progress
ln -s /bin/busybox sbin/pivot_root
ln -s /bin/busybox usr/bin/pkill
ln -s /bin/busybox usr/bin/pmap
ln -s /bin/busybox usr/sbin/popmaildir
ln -s /bin/busybox sbin/poweroff
ln -s /bin/busybox usr/sbin/powertop
ln -s /bin/busybox bin/printenv
ln -s /bin/busybox usr/bin/printf
ln -s /bin/busybox bin/ps
ln -s /bin/busybox usr/bin/pscan
ln -s /bin/busybox usr/bin/pstree
ln -s /bin/busybox bin/pwd
ln -s /bin/busybox usr/bin/pwdx
ln -s /bin/busybox sbin/raidautorun
ln -s /bin/busybox usr/sbin/rdate
ln -s /bin/busybox usr/sbin/rdev
ln -s /bin/busybox usr/sbin/readahead
ln -s /bin/busybox usr/bin/readlink
ln -s /bin/busybox usr/sbin/readprofile
ln -s /bin/busybox usr/bin/realpath
ln -s /bin/busybox sbin/reboot
ln -s /bin/busybox bin/reformime
ln -s /bin/busybox usr/sbin/remove-shell
ln -s /bin/busybox usr/bin/renice
ln -s /bin/busybox usr/bin/reset
ln -s /bin/busybox usr/bin/resize
ln -s /bin/busybox bin/rev
ln -s /bin/busybox bin/rm
ln -s /bin/busybox bin/rmdir
ln -s /bin/busybox sbin/rmmod
ln -s /bin/busybox sbin/route
ln -s /bin/busybox bin/rpm
ln -s /bin/busybox usr/bin/rpm2cpio
ln -s /bin/busybox usr/sbin/rtcwake
ln -s /bin/busybox bin/run-parts
ln -s /bin/busybox sbin/runlevel
ln -s /bin/busybox usr/bin/runsv
ln -s /bin/busybox usr/bin/runsvdir
ln -s /bin/busybox usr/bin/rx
ln -s /bin/busybox usr/bin/script
ln -s /bin/busybox bin/scriptreplay
ln -s /bin/busybox bin/sed
ln -s /bin/busybox usr/sbin/sendmail
ln -s /bin/busybox usr/bin/seq
ln -s /bin/busybox bin/setarch
ln -s /bin/busybox sbin/setconsole
ln -s /bin/busybox usr/sbin/setfont
ln -s /bin/busybox usr/bin/setkeycodes
ln -s /bin/busybox usr/sbin/setlogcons
ln -s /bin/busybox bin/setpriv
ln -s /bin/busybox bin/setserial
ln -s /bin/busybox usr/bin/setsid
ln -s /bin/busybox usr/bin/setuidgid
ln -s /bin/busybox usr/bin/sha1sum
ln -s /bin/busybox usr/bin/sha256sum
ln -s /bin/busybox usr/bin/sha3sum
ln -s /bin/busybox usr/bin/sha512sum
ln -s /bin/busybox usr/bin/showkey
ln -s /bin/busybox usr/bin/shred
ln -s /bin/busybox usr/bin/shuf
ln -s /bin/busybox sbin/slattach
ln -s /bin/busybox bin/sleep
ln -s /bin/busybox usr/bin/smemcap
ln -s /bin/busybox usr/bin/softlimit
ln -s /bin/busybox usr/bin/sort
ln -s /bin/busybox usr/bin/split
ln -s /bin/busybox usr/bin/ssl_client
ln -s /bin/busybox sbin/start-stop-daemon
ln -s /bin/busybox bin/stat
ln -s /bin/busybox usr/bin/strings
ln -s /bin/busybox bin/stty
ln -s /bin/busybox sbin/sulogin
ln -s /bin/busybox usr/bin/sum
ln -s /bin/busybox usr/bin/sv
ln -s /bin/busybox usr/bin/svc
ln -s /bin/busybox usr/sbin/svlogd
ln -s /bin/busybox sbin/swapoff
ln -s /bin/busybox sbin/swapon
ln -s /bin/busybox sbin/switch_root
ln -s /bin/busybox bin/sync
ln -s /bin/busybox sbin/sysctl
ln -s /bin/busybox sbin/syslogd
ln -s /bin/busybox usr/bin/tac
ln -s /bin/busybox usr/bin/tail
ln -s /bin/busybox bin/tar
ln -s /bin/busybox usr/bin/taskset
ln -s /bin/busybox usr/bin/tcpsvd
ln -s /bin/busybox usr/bin/tee
ln -s /bin/busybox usr/bin/telnet
ln -s /bin/busybox usr/sbin/telnetd
ln -s /bin/busybox usr/bin/test
ln -s /bin/busybox usr/bin/tftp
ln -s /bin/busybox usr/sbin/tftpd
ln -s /bin/busybox usr/bin/time
ln -s /bin/busybox usr/bin/timeout
ln -s /bin/busybox usr/bin/top
ln -s /bin/busybox bin/touch
ln -s /bin/busybox usr/bin/tr
ln -s /bin/busybox usr/bin/traceroute
ln -s /bin/busybox usr/bin/traceroute6
ln -s /bin/busybox bin/true
ln -s /bin/busybox usr/bin/truncate
ln -s /bin/busybox usr/bin/tty
ln -s /bin/busybox usr/bin/ttysize
ln -s /bin/busybox sbin/tunctl
ln -s /bin/busybox usr/sbin/ubiattach
ln -s /bin/busybox usr/sbin/ubidetach
ln -s /bin/busybox usr/sbin/ubimkvol
ln -s /bin/busybox usr/sbin/ubirename
ln -s /bin/busybox usr/sbin/ubirmvol
ln -s /bin/busybox usr/sbin/ubirsvol
ln -s /bin/busybox usr/sbin/ubiupdatevol
ln -s /bin/busybox sbin/udhcpc
ln -s /bin/busybox usr/sbin/udhcpd
ln -s /bin/busybox usr/bin/udpsvd
ln -s /bin/busybox sbin/uevent
ln -s /bin/busybox bin/umount
ln -s /bin/busybox bin/uname
ln -s /bin/busybox usr/bin/unexpand
ln -s /bin/busybox usr/bin/uniq
ln -s /bin/busybox usr/bin/unix2dos
ln -s /bin/busybox usr/bin/unlink
ln -s /bin/busybox usr/bin/unlzma
ln -s /bin/busybox usr/bin/unshare
ln -s /bin/busybox usr/bin/unxz
ln -s /bin/busybox usr/bin/unzip
ln -s /bin/busybox usr/bin/uptime
ln -s /bin/busybox usr/bin/users
ln -s /bin/busybox bin/usleep
ln -s /bin/busybox usr/bin/uudecode
ln -s /bin/busybox usr/bin/uuencode
ln -s /bin/busybox sbin/vconfig
ln -s /bin/busybox bin/vi
ln -s /bin/busybox usr/bin/vlock
ln -s /bin/busybox usr/bin/volname
ln -s /bin/busybox usr/bin/w
ln -s /bin/busybox usr/bin/wall
ln -s /bin/busybox bin/watch
ln -s /bin/busybox sbin/watchdog
ln -s /bin/busybox usr/bin/wc
ln -s /bin/busybox usr/bin/wget
ln -s /bin/busybox usr/bin/which
ln -s /bin/busybox usr/bin/who
ln -s /bin/busybox usr/bin/whoami
ln -s /bin/busybox usr/bin/whois
ln -s /bin/busybox usr/bin/xargs
ln -s /bin/busybox usr/bin/xxd
ln -s /bin/busybox usr/bin/xz
ln -s /bin/busybox usr/bin/xzcat
ln -s /bin/busybox usr/bin/yes
ln -s /bin/busybox bin/zcat
ln -s /bin/busybox sbin/zcip
