/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2018-11-16-0cb77c3"
#endif /* AVUTIL_FFVERSION_H */
