#!/bin/sh
#
# Start daemonip
#

chmod 666 /dev/null
chmod 666 /dev/urandom
chmod 666 /dev/ptmx
chown root:root /var/empty

NAME=daemon_ip
DAEMON=/usr/local/bin/daemon_ip
PIDFILE=/var/run/$NAME.pid


case "$1" in
  start)
	printf "Starting ip daemon "
        start-stop-daemon -S -q -m -p $PIDFILE --exec $DAEMON
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping ip daemon: "
        killall -9 $NAME
	echo "OK"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
