#!/bin/sh

# edb platform env setup.
# user led default output 0.
echo 468 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio468/direction
echo 0 > /sys/class/gpio/gpio468/value

echo 469 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio469/direction
echo 0 > /sys/class/gpio/gpio469/value

echo 472 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio472/direction
echo 0 > /sys/class/gpio/gpio472/value

echo 473 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio473/direction
echo 0 > /sys/class/gpio/gpio473/value

#mdev
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

# insmod edb_mod.ko
insmod /system/data/edb_mod.ko
