#!/bin/sh
#
# Start sshd
#

chmod 666 /dev/null
chmod 666 /dev/urandom
chmod 666 /dev/ptmx
chown root:root /var/empty

case "$1" in
  start)
	printf "Starting sshd: "
	chmod 0600 /usr/local/etc/*_key
	chmod 0600 /usr/local/etc/*.pub
	date "2019-07-01"
	/usr/local/bin/sshd
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping sshd: "
	start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/sshd.pid
	echo "OK"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
