obj-$(CONFIG_BITMAIN_NPU)	+= npu/bm_npu.o
obj-$(CONFIG_BM1682_MCU_DRV)	+= mcu/mcu_i2c_drv.o
obj-$(CONFIG_BM1682_WDT_DRV)		+= wdt/bm1682_wdt.o
obj-$(CONFIG_BM1682_I2C_SLAVE_DRV)	+= i2c_slave/bm1682_i2c_slave.o
obj-$(CONFIG_ARCH_BM1682)	+= top/bm1682_top.o
obj-$(CONFIG_BM_SUBSYS_INT_EN)	+= misc/subsys_int.o
obj-$(CONFIG_BM_FAN_SPEED)	+= fan/bm_fan_speed.o
obj-$(CONFIG_BM_EFUSE_DRV)	+= efuse/bm_efuse.o
