obj-$(CONFIG_VIDEO_BITMAIN_VIP)   += bm-vip.o

bm-vip-y := bm_vip_core.o bm_vip_disp.o bm_vip_img.o bm_vip_sc.o bm_vip_dwa.o \
	bm_vip_isp.o \
	vip/reg.o vip/vip_sys.o vip/cmdq.o vip/scaler.o vip/dwa.o vip/isp_drv.o
